version: '3.8'

services:
    php:
        build: .
        env_file:
            -   .env
        container_name: php_container
        volumes:
            -   .:/var/www
        networks:
            -   app-network
        depends_on:
            -   db
        environment:
            - APP_ENV=local
            - APP_DEBUG=${APP_DEBUG}
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=pgsql
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
            - JWT_SECRET=${JWT_SECRET}

    nginx:
        image: nginx:alpine
        container_name: nginx_container
        ports:
            -   '8000:80'
        volumes:
            - ./public:/var/www/public
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
        networks:
            - app-network

    db:
        image: postgres:14.17
        container_name: db_container
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            -   db-data:/var/lib/postgresql/data
            - ./pg_hba.conf:/etc/postgresql/data/pg_hba.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
